@host  = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzc3ODg0MTM2LCJleHAiOjE3Nzc4ODc3MzZ9.YeFpibVrSdG5I77YNVQz1ZZNaD-l86f77mriihlKObc

### Authentication
### Register
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "name": "Femi Ben",
  "email": "test@gmail.com",
  "password": "123456"
}

### Login
POST {{host}}/api/auth/login
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "test@gmail.com",
  "password": "123456"
}